############################################################################################### 공통 설정 시작
#actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "refresh, info, health"

#서버 설정
server:
  shutdown: graceful

---
spring:
  profiles:
    active: local, dev
  
  #db
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://172.105.236.96:3306/dhk
    username: dhk
    password: qwer1234
    
  jpa:
    hibernate:
      naming:
        #논리
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        
        #물리
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:com/dhkim/prj/**/*Mapper.xml
  type-aliases-package: com.dhkim.prj
  
#로깅설정
logging:
  charset:
    console: utf8
    file: utf8
  group:
    application: com.dhkim.prj
  level:
    jdbc.sqltiming: INFO
    jdbc.resultsettable: INFO
    jdbc.sqlonly: OFF
    jdbc.audit: OFF
    jdbc.resultset: OFF
    jdbc.connection: OFF
    application: DEBUG
    root: INFO